name: Build and push Docker image

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker build -t laxeku/bstestje:latest .
        docker login -u laxeku -p ${{ secrets.DOCKER_PASSWORD }}
        docker push laxeku/bstestje:latest

